substitutions:
  name: "printer-display"
  friendly_name: Printer Display

  Outlines: "0" # Setting to 0 will disable all Outlines.
#--------------------------------------------------------------------------------------------------
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
#--------------------------------------------------------------------------------------------------
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
#--------------------------------------------------------------------------------------------------
# Enable logging
logger:
  logs:
    component: ERROR
#--------------------------------------------------------------------------------------------------
# Enable Home Assistant API
api:
  encryption:
    key: !secret haapi_key
#--------------------------------------------------------------------------------------------------
ota:
  - platform: esphome
    password: !secret ota_password
#--------------------------------------------------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: off

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret haapi_password
#--------------------------------------------------------------------------------------------------
captive_portal:
#--------------------------------------------------------------------------------------------------
psram:
  mode: octal
  speed: 80MHz
#--------------------------------------------------------------------------------------------------
i2c:
  - id: i2cbus_a
    sda: GPIO08
    scl: GPIO09
    scan: True
#--------------------------------------------------------------------------------------------------
ch422g:
  - i2c_id: i2cbus_a
    id: ch422g_hub
#--------------------------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "${friendly_name} Restart"
#---------------------------------------------------
  - platform: gpio
    name: ${friendly_name} Backlight
    id: backlight_switch
    pin:
      ch422g: ch422g_hub
      number: 2
      allow_other_uses: true
      mode:
        output: true
    inverted: false
    restore_mode: ALWAYS_ON
#--------------------------------------------------------------------------------------------------
number:
  - platform: template
    name: Screen Lux Threshold
    optimistic: true
    id: display_threshold
    unit_of_measurement: "lx"
    initial_value: .5
    restore_value: true
    min_value: 0
    max_value: 1000
    step: 0.1
    mode: box
#--------------------------------------------------------------------------------------------------
sensor:
- platform: wifi_signal
  name: "${friendly_name} Signal Strength"
  update_interval: 60s
#---------------------------------------------------
- platform: homeassistant
  id: office_brightness
  entity_id: sensor.eddys_office_ambient_light
  on_value:
    then:
    - if:
        condition:
          lambda: 'return (x < (id(display_threshold).state));'
        then:
          - switch.turn_off: backlight_switch
        else:
          - switch.turn_on: backlight_switch
#---------------------------------------------------
- platform: ccs811
  address: 0x5A
  i2c_id: i2cbus_a
  update_interval: 60s
  baseline: 0x07BE
  temperature: printer_temperature
  humidity: printer_humidity
  eco2:
    name: "${friendly_name} eCO2"
    id: printer_eco2
    on_value:
      - lvgl.label.update:
          id: printer_eCO2_label
          text:
            format:  "%0.0f"
            args: [ 'x' ]  
  tvoc:
    name: "${friendly_name} VOC"
    id: printer_voc
    on_value:
      - lvgl.label.update:
          id: display_VOC_label
          text:
            format:  "%0.0f"
            args: [ 'x' ]  
#---------------------------------------------------
- platform: bme280_i2c
  address: 0x76
  i2c_id: i2cbus_a
  update_interval: 60s

  temperature:
    name: "${friendly_name} Temperature"
    oversampling: 16x
    id: printer_temperature
    unit_of_measurement: "°F"
    state_class: measurement
    device_class: temperature
    filters:
      - lambda: return x * (9.0/5.0) + 32.0; # Convert C to F
    on_value:
      - lvgl.label.update:
          id: printer_temp_label
          text:
            format:  "%.0f°F"
            args: [ 'x' ]  

  humidity:
    name: "${friendly_name} Humidity"
    id: printer_humidity
    unit_of_measurement: "%"
    state_class: measurement
    device_class: humidity
    on_value:
      - lvgl.label.update:
          id: printer_humidity_label
          text:
            format:  "%.0f%%"
            args: [ 'x' ]  
#--------------------------------------------------------------------------------------------------
text_sensor:
- platform: wifi_info
  ip_address:
    name: ${friendly_name} IP
  ssid:
    name: ${friendly_name} SSID
  bssid:
    name: ${friendly_name} BSSID
  mac_address:
    name: ${friendly_name} Mac
#--------------------------------------------------------------------------------------------------
time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      - script.execute: time_update
      - script.execute: date_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update
      - hours: 0
        minutes: 0
        seconds: 0
        then:
          - script.execute: date_update
#---------------------------------------------------------------------------------------------------
font:
  - file: "fonts/G7_Segment7_S5.ttf"
    id: big_seven_seg
    size: 270
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9","-",
      "\u0020", #space
      "\u003A", #colon
      ]
#---------------------------------------------------
  - file:
      type: gfonts
      family: Concert One
      weight: regular
    id: concert_34
    size: 34
    bpp: 4
    extras:
      - file: "gfonts://Concert One"
        glyphs: [µ,³]
#---------------------------------------------------
  - file:
      type: gfonts
      family: Concert One
      weight: regular
    id: two_cell
    size: 130
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9",
      "-",".","%","°",
      "F","S","t","e","a","d","y","c","o","v",
      "\u0020", #space
      "\u003A", #colon
      ]
#---------------------------------------------------
  - file:
      type: gfonts
      family: Concert One
      weight: regular
    id: unit_measurement
    size: 50
    bpp: 4
    glyphs: [
      "0","1","2","3","4","5","6","7","8","9",
      "-",".","%","°",
      "c","o","v",
      "\u0020", #space
      "\u003A", #colon
      ]
#---------------------------------------------------------------------------------------------------
display:
  - platform: rpi_dpi_rgb
    id: my_display
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 800
      height: 480
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    enable_pin:
      ch422g: ch422g_hub
      number: 2
      allow_other_uses: true
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 10 #30
    hsync_front_porch: 20 #210 
    hsync_pulse_width: 10 #30
    vsync_back_porch: 10 #4
    vsync_front_porch: 10 #4
    vsync_pulse_width: 10 #4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7
#--------------------------------------------------------------------------------------------------
touchscreen:
  platform: gt911
  address: 0x5D
  i2c_id: i2cbus_a
  id: my_touchscreen
  update_interval: 16ms
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: output
  on_touch:
    - switch.turn_on: backlight_switch
    - script.execute: time_update
    - lvgl.resume:
    - lvgl.widget.redraw:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
#--------------------------------------------------------------------------------------------------
lvgl:
  displays:
    - my_display
  buffer_size: 25%
  disp_bg_color: 0x000000
#---------------------------------------------------
  touchscreens:
    - touchscreen_id: my_touchscreen
#---------------------------------------------------
  style_definitions:
    - id: header
      align: CENTER
      text_align: CENTER
      grid_cell_x_align: Stretch
      grid_cell_y_align: CENTER
      bg_color: 0x000000 #0x2F8CD8
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      text_font: concert_34
      border_color: 0x000000 #0x0077b3
      text_color: 0x323AA8
#---------------------------------------------------
    - id: footer
      align: CENTER
      text_align: CENTER
      grid_cell_x_align: Stretch
      grid_cell_y_align: CENTER
      bg_color: 0x000000 #0x2F8CD8
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      text_font: montserrat_28
      border_color: 0x000000 #0x0077b3
      text_color: 0x323AA8
#---------------------------------------------------
    - id: time_format
      bg_color: 0x000000
      bg_opa: COVER
      border_opa: TRANSP
      grid_cell_x_align: Stretch
      grid_cell_y_align: CENTER
      outline_color: 0xFFFF00
      outline_width: ${Outlines}
      text_align: CENTER
      align: CENTER
      text_font: big_seven_seg
      border_color: 0x000000
      text_color: 0x323AA8
#---------------------------------------------------
    - id: two_cell_style
      grid_cell_x_align: STRETCH
      grid_cell_y_align: CENTER
      text_font: two_cell
      text_color: 0x323AA8
      text_align: CENTER
      text_opa: 100%
      pad_all: 0
      pad_row: 0
      pad_column: 0
      outline_width: ${Outlines}
      outline_color: 0xFFFF00
      width: 95%
#      height: 55%
#      height: 160
#---------------------------------------------------
    - id: unit_measurement_style
      grid_cell_x_align: STRETCH
      grid_cell_y_align: CENTER
      text_font: unit_measurement
      text_color: 0x323AA8
      text_align: CENTER
      text_opa: 100%
      pad_all: 0
      pad_row: 0
      pad_column: 0
      outline_width: ${Outlines}
      outline_color: 0xFFFF00
      width: 95%
#      height: 55%
#      height: 160
#---------------------------------------------------
    - id: footer_button
      grid_cell_x_align: Stretch
      grid_cell_y_align: CENTER
      bg_opa: TRANSP
      border_opa: TRANSP
      shadow_opa: TRANSP
      pad_all: 0
      pad_row: 0
      pad_column: 0
      outline_color: 0x00FF00
      outline_width: ${Outlines}
#--------------------------------------------------------------------------------------------------
# Day/Date display
  top_layer:
    widgets:
        - obj:
            align: top_mid
            width: 790
            height: 50
            pad_all: 0
            bg_opa: TRANSP
            border_opa: TRANSP
            outline_width: ${Outlines}
            outline_color: 0xFF0000
            layout:
              type: grid
              grid_columns: [FR(50),FR(25),FR(25)]
              grid_rows: [FR(1)]
            widgets:
              - label:
                  id: time_label
                  styles: header
                  text: "--:--"
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  text_align: CENTER
              - label:
                  id: day_label
                  styles: header
                  text: "Fri"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  text_align: right
              - label:
                  id: date_label
                  styles: header
                  text: "Oct 13"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  text_align: left
#---------------------------------------------------
# Navigation buttons
        - obj:
            align: bottom_mid
            width: 790
            height: 50
            pad_all: 0
            bg_opa: TRANSP
            border_opa: TRANSP
            outline_width: ${Outlines}
            outline_color: 0xFF0000
            layout:
              type: grid
              grid_columns: [FR(1),FR(1),FR(1)]
              grid_rows: [FR(1)]
            widgets:
              - button:
                  id: page_prev_button
                  styles: footer_button
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  on_press:
                    then:
                      lvgl.page.previous:
                  widgets:
                    - label:
                        id: page_prev
                        styles: footer
                        text: "\uF053"
              - button:
                  id: page_home_button
                  styles: footer_button
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  on_press:
                    then:
                      lvgl.page.show: main_page
                  widgets:
                    - label:
                        id: page_home
                        styles: footer
                        text: "\uF015"
              - button:
                  id: page_next_button
                  styles: footer_button
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  on_press:
                    then:
                      lvgl.page.next:
                  widgets:
                    - label:
                        id: page_next
                        styles: footer
                        text: "\uF054"
#--------------------------------------------------------------------------------------------------
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        - obj:
            align: CENTER
            width: 790
            height: 370
            bg_opa: TRANSP
            border_opa: TRANSP
            outline_width: ${Outlines}
            outline_color: 0xFF0000
            pad_all: 0
            x: 0
            y: 0
            layout:
              type: grid
              grid_columns: [FR(35),FR(15),FR(35),FR(15)]
              grid_rows: [FR(1),FR(1)]
              pad_column: 0
              pad_row: 0
            widgets:
              - label:
                  id: printer_temp_label
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  text: "00°F"
                  styles: two_cell_style
                  grid_cell_column_span: 2
              - label:
                  id: printer_humidity_label
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  text: "00%"
                  styles: two_cell_style
                  grid_cell_column_span: 2
              - label:
                  id: printer_eCO2_label
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  text: "---"
                  styles: two_cell_style
              - label:
                  id: printer_eCO2_um
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  text: "co2"
                  styles: unit_measurement_style
              - label:
                  id: display_VOC_label
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 1
                  text: "---"
                  styles: two_cell_style
              - label:
                  id: display_VOC_um
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 1
                  text: "voc"
                  styles: unit_measurement_style
#---------------------------------------------------
    - id: time_page
      bg_color: 0x000000
      widgets:
        - obj:
            align: CENTER
            width: 790
            height: 370
            bg_opa: TRANSP
            border_opa: TRANSP
            outline_width: ${Outlines}
            outline_color: 0xFF0000
            pad_all: 0
            x: 0
            y: 0
            layout:
              type: grid
              grid_columns: [FR(1)]
              grid_rows: [FR(1)]
            widgets:
              - label:
                  id: display_time
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  text: "--:--"
                  styles: time_format
#---------------------------------------------------------------------------------------------------
script:
# This script updates the time
#            snprintf(time_buf, sizeof(time_buf), "%2d:%02d%s", hour_12, now.minute, is_pm ? "pm" : "am"); // This does have the ap/pm flag
  - id: time_update
    then:
      - lvgl.label.update:
          id:
            - display_time
            - time_label
          text: !lambda |-
            static char time_buf[17];
            auto now = id(esptime).now();            
            bool is_pm = now.hour >= 12;
            int hour_12 = now.hour % 12;
            if (hour_12 == 0) {
                hour_12 = 12;
            }
            snprintf(time_buf, sizeof(time_buf), "%2d:%02d", hour_12, now.minute); // This does NOT have the am/pm flag
            return time_buf;
#---------------------------------------------------
#This script updates the Day and Date
  - id: date_update
    then:
      - lvgl.label.update:
          id: 
            - date_label
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[8];
            auto now = id(esptime).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id:
            -  day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(esptime).now().day_of_week - 1];
#---------------------------------------------------------------------------------------------------